# define base php-apache image for development environment
FROM php:8.4-apache

# set container working directory
WORKDIR /var/www

# install required packages
RUN apt-get update && apt-get install -y \
    libicu-dev \
    rpm
    
# install intl extension
RUN docker-php-ext-install intl

# install OPCache extension
RUN docker-php-ext-install opcache
